### ISSUE TITLE
redirected to /maintenance after update

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/wishthis#105]
## Branch
On which branch did you notice this bug?
- [ ] stable
- [ ] release-candidate
- [x] develop

## Description
I'm not sure how to reproduce, since I'm using the docker image and therefore have no way to revert to an older version and test if this can be reliably reproduced. But I guess for local development you could go back to a specific version just using git. I was on the dev-branch from roughly the 21. of July this year and pulled the latest develop docker image from 10 days ago (should be 4. of October I guess)

I also tried switching to stable and release candidate:

- release-candidate results in the same behaviour
- stable gives me a redirection error because it's redirecting infinitely from  /?page=home to /?page=maintenance and back

## Logs
logs are looking pretty normal. db logs included just for sake of completeness:

wishthis_db  | 2023-10-14 13:36:40+02:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
wishthis_db  | 2023-10-14 13:36:41+02:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
wishthis_db  | 2023-10-14 13:36:41+02:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server  started.
wishthis_db  | 2023-10-14T11:36:41.562301Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
wishthis_db  | 2023-10-14T11:36:41.562549Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33-0ubuntu0.22.04.2) starting as process 1
wishthis_db  | 2023-10-14T11:36:41.575787Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
wishthis_db  | 2023-10-14T11:36:41.845460Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
wishthis_db  | 2023-10-14T11:36:42.295685Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
wishthis_db  | 2023-10-14T11:36:42.295802Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
wishthis_db  | 2023-10-14T11:36:42.311453Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
wishthis_db  | 2023-10-14T11:36:42.370988Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
wishthis_db  | 2023-10-14T11:36:42.371230Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33-0ubuntu0.22.04.2'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu).

wishthis     | Starting Mail Transport Agent (MTA): sendmail.
wishthis     | Removing user 'www-data' from group 'sudo' ...
wishthis     | Done.
wishthis     | [Sat Oct 14 13:36:44.488578 2023] [mpm_prefork:notice] [pid 75] AH00163: Apache/2.4.57 (Debian) PHP/8.1.24 configured -- resuming normal operations
wishthis     | [Sat Oct 14 13:36:44.488659 2023] [core:notice] [pid 75] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

I'd be happy to help if you need me to test something or any further informations

**Comment by grandeljay** [comment]
Hey @cryptogeek13,

thank you for reporting this!

Have you tried logging in? Usually there are some changes that need to be done to the database. Once you're in, there should be a migration button for the database.

Does that work?

**Comment by proud-nerd** [comment]
That triggers navigation but I end up at /maintenance again. I guess I get redirected, but can' check right now because I'm on mobile.

**Comment by proud-nerd** [comment]
Can I trigger database migration directly calling the API?

**Comment by grandeljay** [comment]
> That triggers navigation but I end up at /maintenance again. I guess I get redirected, but can' check right now because I'm on mobile.

Are you the instance admin? The redirect to the maintenance page is intended behaviour. The administrator should upgrade the database after logging in. It should be visible on the maintenance page if you are logged in as administrator.

In case it isn't (for whatever reason):

1. Check if your `power` is set to 100 in the `users` table or
2. Run all of the SQL files manually which are higher than your current version: in [/src/update](https://github.com/wishthis/wishthis/tree/develop/src/update).

Let me know if any of this helps you!

**Comment by proud-nerd** [comment]
Well, I think I am the instance admin but since I can't get to the login page I can't tell if I could start the migration. I''ll try and do the manual steps tomorrow and check my permissions in database while I'm at it. But in my head my user rights could only matter if I managed to log in.

**Comment by proud-nerd** [comment]
I tried again today and funnily enough this time the login page opened when I clicked the login button, even though nothing changed (same machine, browser, container than yesterday). After logging in, I still got redirected to /maintenance without being logged in. But second try worked and got me to /update.

There again I had to click the migration button to V1.1.0 two times, even though I got a green toast message after the first time.

Now I'm back to normal, but the first couple changes to a wish didn't get reflected, even though I got a success toast message. I had to force reload without caching a few times (strg+F5) to make it work.

There is definitely something wrong with my setup, could it be some kind of caching issue?

**Comment by grandeljay** [comment]
I've noticed caching issues on the `stable` branch but it should work on the `release-candidate` and `develop` branch. Which one are you currently using?

**Comment by proud-nerd** [comment]
I'm using the `release-candidate` docker image. If your changes on release-candidate and develop are recent, it might be a little bit behind? [Docher Hub](https://hub.docker.com/r/hiob/wishthis) says all images are from 11 days ago

**Comment by grandeljay** [comment]
Unfortunately, I don't know how frequently the images update but I [removed caching about three weeks ago](https://github.com/wishthis/wishthis/commit/34ab46c66f58586da41a0a00e269c32c4fbd9ec2) so it should already be included in the RC image.

Would you mind trying it in a non chromium based browser (such as Firefox)? I've noticed that Google Chrome in particular has very aggressive caching and even ignores some HTTP headers, which state that the document has changed and needs updating.

**Comment by proud-nerd** [comment]
Actually I am already using Firefox. But I just checked and can confirm that those lines you removed in the linked commit are still present in my image, so I guess that's the problem. Should I open an issue in the [docker repo](https://github.com/wishthis/docker)?

**Comment by grandeljay** [comment]
Yes, please!

**Comment by proud-nerd** [comment]
Alright, this can be closed then. Thanks for your help analyzing this
