### ISSUE TITLE
Can't set a price

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/wishthis#107]
## Branch
On which branch did you notice this bug?
- [ ] stable
- [x] release-candidate
- [x] develop

## Description
When I enter a price for a wish and click save, it isn't displayed. When I then edit that same wish again, the price input is empty.

I do get a success toast after saving and there are no errors in console or network tab.

**Comment by grandeljay** [comment]
Thank you for using the release candidate and reporting this! I was able to reproduce this and will look into it.

**Comment by phlbnks** [comment]
I haven't tried to look at the code - but I have the issue too, and can confirm the Price initially gets saved to the database for me. But it isn't loaded when viewing/editing. This means that if you edit the Wish to change other info then a blank Price gets saved over the previously correct Price in the dB, wiping it.

**Comment by grandeljay** [comment]
I've updated `develop` and `release-candidate` can you confirm that the fix worked?

**Comment by phlbnks** [comment]
Quick test but looks good to me testing develop 🙏 
Thanks for the quick fix!
