### ISSUE TITLE
Switching channels doesn't (fully) work

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/wishthis#108]
## Branch
On which branch did you notice this bug?
- [x] stable
- [x] release-candidate
- [ ] develop

## Description

Browser: Firefox 118.0.2

### stable
- log in to wishthis.online
- go to profile -> preferences 
- change channel to 'release-candidate'
- click save

I'd expect being navigated to rc.wishthis.online. Instead, that does happen only if I trigger another navigation by using the home button or going to my wishlists.
I also end up with a blank page after being redirected. Reloading the page fixes that.
![Screenshot](https://i.ibb.co/4jnqByB/Screenshot-20231015-160550.png)

### release-candidate

- log in to rc.wishthis.online
- go to profile -> preferences 
- change channel to 'stable'
- click save

this time nothing happens. I stay on rc.wishlist.online and can navigate around as long as I want, log out, log back in, hit strg+f5 without being redirected to wishlist.online

**Comment by grandeljay** [comment]
I believe this to be related to the caching problems I mentioned in https://github.com/wishthis/wishthis/issues/105#issuecomment-1763398482. Assuming that's the case, a release on the `stable` branch should fix this.
