### ISSUE TITLE
"Forgot password?": Nothing happens when submitting

### ISSUE THREAD

**Issue by bebatut** [wishthis/wishthis#175]
## Branch
On which branch did you notice this bug?
- [X] stable
- [ ] release-candidate
- [ ] develop

## Description

When I clicked on "Send email" in the "Forgot password?" part online, I got a white page and no email
<img width="1438" alt="Screenshot 2023-11-08 at 11 13 33" src="https://github.com/wishthis/wishthis/assets/1842467/1e3c9666-b297-4cce-8ae1-58ca3236a875">

**Comment by grandeljay** [comment]
Hello @bebatut,

thank you for reporting this! I'll look into this shortly.

**Comment by grandeljay** [comment]
Can you please try again and confirm that it works now?

**Comment by bebatut** [comment]
It looks better but I did not get any email (even in spam)

![image](https://github.com/wishthis/wishthis/assets/1842467/07ed3e85-884c-4b8d-a76c-5cf947e2adf8)

**Comment by grandeljay** [comment]
You'll have to use the e-mail you registered with for the system to find you.

**Comment by bebatut** [comment]
I used the same email, but got nothing

**Comment by grandeljay** [comment]
Interesting. I tried it on myself and got the email. I'm starting to think this is related to your provider. I'm willing to bet they have spam filtering on a server level which could explain why you never get the password reset email. I'm stumped for now, sorry.

In the meantime, I'll send you the link to reset your password manually. Try this: https://onetimesecret.com/secret/jc68zqj3vbjejs5qc0dowsnxjynuf9 (link expires after visiting it once).

Let me know if that works.

**Comment by bebatut** [comment]
I checked in the spam. Nothing :(

But your link worked. Thanks a lot!

**Comment by grandeljay** [comment]
I've tried resetting my password with a gmail address and also didn't get an email. I think gmail (and probably other providers) are automatically filtering it out as spam.

The password reset email should ideally be sent with a email delivery service to solve this. Closing this for now, as that's a separate issue/feature.
