### ISSUE TITLE
Can not access my lists

### ISSUE THREAD

**Issue by bebatut** [wishthis/wishthis#176]
## Branch
On which branch did you notice this bug?
- [X] stable
- [ ] release-candidate
- [ ] develop

## Description

Once connected on the website, I can not access the lists I created when I click on "My lists" in the "Whishlist" dropdown menu

**Comment by grandeljay** [comment]
Hi,

thanks again for reporting this. Can you please share the errors from the browser console?

This seems to be related to the latest update. Were you using wishthis in the last version (`1.0.0`) too? Did it work for you then?

**Comment by bebatut** [comment]
There is no error on the browser consol
I am using https://wishthis.online/

**Comment by grandeljay** [comment]
I am having trouble reproducing this, what browser are you using?

**Comment by bebatut** [comment]
I am using Firefox

**Comment by grandeljay** [comment]
Can you please try opening the developer tools again and temporarily disable http cache. Does that change anything?

![image](https://github.com/wishthis/wishthis/assets/45571053/4aa28a43-b85a-47fb-a216-7c55b230b459)

**Comment by bebatut** [comment]
It works now :) Thanks

**Comment by grandeljay** [comment]
Glad it works!

I'll leave this issue open a bit since this is already the second report of an issue related to HTTP cache. I probably messed up a header in the last version.
