### ISSUE TITLE
Expected behavior to be able to access lists of other users?

### ISSUE THREAD

**Issue by bebatut** [wishthis/wishthis#177]
## Branch
On which branch did you notice this bug?
- [X] stable
- [ ] release-candidate
- [ ] develop

## Description

When I change the number in the URL, e.g. https://wishthis.online/wishlists/622, I can see the lists of other users.
Is it an expected behavior?

**Comment by grandeljay** [comment]
Hi,

thanks again for another bug report!

This is not intended at all and I will look into it.
