### ISSUE TITLE
Share link - Error 403 forbidden 

### ISSUE THREAD

**Issue by bebatut** [wishthis/wishthis#179]
## Branch
On which branch did you notice this bug?
- [x] stable
- [ ] release-candidate
- [ ] develop

## Description

When I open the share link (while not logged in), I got the message "Error 403 forbidden" and then an empty list

![Screenshot_20231112-090015.png](https://github.com/wishthis/wishthis/assets/1842467/b20203a4-0da5-4626-ad2b-0b016ed48a9f)

**Comment by grandeljay** [comment]
Thanks again for the bug report!

**Comment by bebatut** [comment]
It works now. Thanks 😄

**Comment by ujean1801** [comment]
Hi, I am getting the same bug. I see it works now, but what did you do to make it work? Same 403 error issue with an empty list. It opens the list OK for the first time (although no wishes in the list) and then upon refreshing it gives 403 error.

**Comment by grandeljay** [comment]
@ujean1801 are using wishthis from your desktop? Could you try opening developer tools on disabling http cache (as described in https://github.com/wishthis/wishthis/issues/176#issuecomment-1804017525)?

**Comment by ujean1801** [comment]
> @ujean1801 are using wishthis from your desktop? Could you try opening developer tools on disabling http cache (as described in [#176 (comment)](https://github.com/wishthis/wishthis/issues/176#issuecomment-1804017525))?

Hi, I did switch off caching and it works. Is this a temporary workaround? I am just thinking if I am to share the link to people, who don't know how to use the dev tools, they'd not be able to access the page...  Is there any way to have a more permanent fix without the need to use the above tweak>

Thanks a lot for the help!

**Comment by ujean1801** [comment]
It's working. I believe you fixed the code and I repulled the image. Thanks a ton!
