### ISSUE TITLE
Error thrown when logging into deleted user

### ISSUE THREAD

**Issue by ChrisLane** [wishthis/wishthis#184]
## Branch
On which branch did you notice this bug?
- [ ] stable
- [ ] release-candidate
- [x] develop (docker image v1.1.0)

## Description
How can the bug be reproduced? If you received an error or similar, please add it here.
1. Started a fresh install of WishThis
2. Registered a user
3. Logged in as the user
4. Deleted the user via the profile page
5. Attempted to log in to the user

The following error was shown in place at the `/login` destination after attempting to login to the deleted user.
```
 Fatal error: Uncaught Error: Typed property wishthis\User::$id must not be accessed before initialization in /var/www/html/src/classes/wishthis/User.php:419 Stack trace: #0 /var/www/html/src/pages/login.php(21): wishthis\User->logIn('wishthis@chrislane...', 'b9e38b3576e35dd...', true) #1 /var/www/html/index.php(165): require('/var/www/html/s...') #2 {main} thrown in /var/www/html/src/classes/wishthis/User.php on line 419
```

**Comment by grandeljay** [comment]
Hey @ChrisLane! Thank you for service! I will look into this.
