### ISSUE TITLE
Improve styling on the "Keep me logged in" checkbox

### ISSUE THREAD

**Issue by ChrisLane** [wishthis/wishthis#189]
## Is your feature request related to a problem? Please describe
I am unable to tell what state the "Keep me logged in" checkbox is in.

## Describe the solution you'd like
**Preference**
Checkboxes that do not change anything until the form is submitted should be styled as plain checkboxes where the box can be visibly/clearly checked or unchecked.
e.g. https://mui.com/material-ui/react-checkbox/

**Backup solution**
If you really want to keep the checkbox visually looking like a switch, a colour change when the option is enabled would make the enablement clearer e.g. https://mui.com/material-ui/react-switch/

## Disclaimer
wishthis is entirely built in my free time, mostly without any pay or code contributors. While I am doing my best to make wishthis a great product for everybody, adding new features takes up my free time outside of my full time job.

- [x] I understand that wishthis depends on volunteer work and that I am not entitled to any kind of support

**Comment by grandeljay** [comment]
Hey @ChrisLane,

thanks for this!

I presume, you are using the dark theme? For me it looks fine in the light theme:

| Unchecked                                                                                           | Checked                                                                                             |
| --------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| ![image](https://github.com/wishthis/wishthis/assets/45571053/52e78c05-7c62-4cf6-8459-7c815c9f6c6e) | ![image](https://github.com/wishthis/wishthis/assets/45571053/180b3b6f-68b2-4884-b360-cee822f897b5) |

What do you think if I correct it like this?
| Unchecked | Checked |
| --------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- |
| ![image](https://github.com/wishthis/wishthis/assets/45571053/5d77b6d7-2994-442f-8a29-84ae1646863a) | ![image](https://github.com/wishthis/wishthis/assets/45571053/71a7d409-49fc-48c6-8fc5-9a852f56f00a) |

**Comment by ChrisLane** [comment]
Yes, I was using the dark theme and that looks good to me! :)
