### ISSUE TITLE
Need to clear cookies to log back in after inactivity

### ISSUE THREAD

**Issue by SoskaCream** [wishthis/wishthis#191]
## Branch
On which branch did you notice this bug?
- [X] stable (1.1.1)
- [ ] release-candidate
- [ ] develop

## Description
When logging in (Chrome & Firefox desktop & mobile tested), the session may expires after some inactivity and redirect to the home page. But then it isn't possible to access to the https://wishthis.online/login page, as it reloads the home page.

Workaround is to clear cache & cookie for Wishthis. It is then possible to access the login page.

It is possible to access the login page through the log-out option, however (loging-out, then going to the login page works).

## Disclaimer
wishthis is entirely built in my free time, mostly without any pay or code contributors. While I am doing my best to help out everybody, I cannot guarantee that I will find the time or have the competence to help you out.

I greatly appreciate that you are filing a bug report, these help tremendously! Thank you!

- [X] I understand that wishthis depends on volunteer work and that I am not entitled to any kind of support

**Comment by grandeljay** [comment]
Thanks @SoskaCream!

I've recently started an attempt to fixing the login by rewriting the way sessions are handled in wishthis here https://github.com/wishthis/wishthis/commit/0b87dc3cac7ea8553c59f6fd3b87dcfa72abfb3d (unreleased). 

I'm still playing around with it though, as I'm not sure it works reliably yet 🤔

**Comment by grandeljay** [comment]
I've just pushed my changes to the release candidate, let me know if you're still having issues!
