### ISSUE TITLE
Cannot login after updating

### ISSUE THREAD

**Issue by ChrisLane** [wishthis/wishthis#192]
## Branch
On which branch did you notice this bug?
- [ ] stable
- [ ] release-candidate
- [x] develop

## Description
After updating my local docker image, I can no longer login to my WishThis.
I get the following error:
```
Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session' at row 1 in /var/www/html/src/classes/wishthis/Database.php:65 Stack trace: #0 /var/www/html/src/classes/wishthis/Database.php(65): PDOStatement->execute() #1 /var/www/html/src/classes/wishthis/User.php(642): wishthis\Database->query('INSERT INTO `se...', Array) #2 /var/www/html/src/classes/wishthis/User.php(414): wishthis\User->refreshSession(1) #3 /var/www/html/src/pages/login.php(21): wishthis\User->logIn('chris@{redacted}...', '{redacted}...', true) #4 /var/www/html/index.php(138): require('/var/www/html/s...') #5 {main} thrown in /var/www/html/src/classes/wishthis/Database.php on line 65
```
Side note: it would be ideal if errors did not contain my password attempt hash.

## Disclaimer
wishthis is entirely built in my free time, mostly without any pay or code contributors. While I am doing my best to help out everybody, I cannot guarantee that I will find the time or have the competence to help you out.

I greatly appreciate that you are filing a bug report, these help tremendously! Thank you!

- [x] I understand that wishthis depends on volunteer work and that I am not entitled to any kind of support

**Comment by grandeljay** [comment]
Hey @ChrisLane,

thank you for using the `develop` branch and filing this report!

I'm sorry about the error, it seems your session id is longer than expected. Are you using nginx by chance?

If you're looking for a quick "fix", you could alter your database structure to avoid the error again:
```sql
  ALTER TABLE `sessions`
CHANGE COLUMN `session` `session` VARCHAR(255) NOT NULL;
```
(untested)

**Comment by grandeljay** [comment]
I've done some research and found that the session id length depends on two different settings:
* [session.hash_function](http://php.net/manual/en/session.configuration.php#ini.session.hash-function)
* [session.hash_bits_per_character](http://php.net/manual/en/session.configuration.php#ini.session.hash-bits-per-character).

What do you have set for those?

**Comment by ChrisLane** [comment]
I've not changed anything so it should just be whatever it's set to in the docker image.

**Comment by grandeljay** [comment]
Alright, it's probably the default then. I also missed that these values don't exist any more. They were removed in PHP 7.1 😵‍💫 

I'm not familiar with docker but it seems to use Apache over Nginx, so it can't be that either. Back to square one then.. 🤔

**Comment by grandeljay** [comment]
I think I found the issue!

I haven't updated the installer yet, it creates the `sessions.session` column with a maximum of 32 chars:
https://github.com/wishthis/wishthis/blob/8c0b0b05c28c3a5a7a6aaa5df6dc350716e2a13a/src/pages/install.php#L387

In the next version, 60 are required and expected since I have rewritten the authentication process:
https://github.com/wishthis/wishthis/blob/8c0b0b05c28c3a5a7a6aaa5df6dc350716e2a13a/src/update/1-2-0.sql#L4-L5

It seems you are either using a fresh install or haven't run the updater/maintenance yet.

**Comment by ChrisLane** [comment]
I wasn't aware there was an updater.
Is that what is being referred to in the README?
> Note: after pulling updates for a new version you might be prompted to update the database schema in the wishthis user interface (if necessary). Make sure you are logged in.

I'm unable to get the prompt to update the DB schema because I cannot login :P
I had thought that kind of thing would run automatically after an update.

**Comment by grandeljay** [comment]
> I wasn't aware there was an updater.
> Is that what is being referred to in the README?
>
>> Note: after pulling updates for a new version you might be prompted to update the database schema in the wishthis user interface (if necessary). Make sure you are logged in.

Yeah

> I'm unable to get the prompt to update the DB schema because I cannot login :P

Oh right 🤦🏼‍♂️. Since you seem to be using docker, it's probably a difficult problem to solve 🤔. At least for me. I know nothing of docker.

> I had thought that kind of thing would run automatically after an update.

You should be redirected to a maintenance page with a note prompting you to log in. Do you at least see that?

**Comment by proud-nerd** [comment]
if anyone stumbles across this, here is what I did to fix this locally within my docker container:

1. Open bash inside of your database container 
`$ docker compose exec -it <db-container-name> /bin/bash`

2. navigate to where the database is located. This might differ from your setup, if you are unsure, look at your docker compose file. There should be a mount point to persist your data.
`# cd /var/lib/mysql`

3. enter mysql-cli
`# mysql -u <database-user> -p`

4. select the correct database (again, this might differ from your setup, look at your wishthis config.php)
`mysql> USE wishthis;`

5. apply the [migration suggested](https://github.com/wishthis/wishthis/issues/192#issuecomment-1908107194) by @grandeljay

After that I was able to log in and start the migration from the maintenance page.

**Comment by grandeljay** [comment]
> apply the https://github.com/wishthis/wishthis/issues/192#issuecomment-1908107194 by @grandeljay

I'd also like to add that I the `release-candidate` has been updated in the meantime, so if you are using it the steps mentioned in my https://github.com/wishthis/wishthis/issues/192#issuecomment-1908107194 _should_ no longer be necessary.

**Comment by Ruthalas** [comment]
I just wanted to chime in and note that I had the same issue where the database migration was inaccessible because I couldn't log in to begin it. The fix provided by @cryptogeek13 and @grandeljay worked to resolve the log in issue, at which point I could run the migration.

I did try to set my docker to pull from release-candidate prior to taking those steps, but that did not change anything.
(I am not sure if it was meant to resolve that issue retroactively or not.)
