### ISSUE TITLE
Using an emoji as a list name results in a success message and a list named "????"

### ISSUE THREAD

**Issue by Deuxis** [wishthis/wishthis#194]
## Branch
On which branch did you notice this bug?
- [x] stable (I think? The one deployed on the website, 1.1.1)
- [ ] release-candidate
- [ ] develop

## Description
1. Create a new list (or rename an existing one) to an emoji (for example "🤤")
2. See results

## Disclaimer
wishthis is entirely built in my free time, mostly without any pay or code contributors. While I am doing my best to help out everybody, I cannot guarantee that I will find the time or have the competence to help you out.

I greatly appreciate that you are filing a bug report, these help tremendously! Thank you!

- [x] I understand that wishthis depends on volunteer work and that I am not entitled to any kind of support

**Comment by grandeljay** [comment]
Hello @Deuxis and thank you for reporting this!

I was able to reproduce the error and can confirm this bug. If you would like to fix it immediately yourself (without waiting for the next release), you can by changing one line of code, as described in: https://github.com/wishthis/wishthis/commit/71aa1fe40118f6f7333549a265502e715f964eee.
