### ISSUE TITLE
Correct Portuguese Translations

### ISSUE THREAD

**Issue by ImAndr0meda** [wishthis/wishthis#201]
## Portuguese PT-PT Translation

Hello, I am a user and a fan of wishthis and I have noticed that some of the PT Translations are wrong, and I was wondering if I can translate it correctly? :)

- [ ✓ ] I understand that wishthis depends on volunteer work and that I am not entitled to any kind of support.

**Comment by ivangomes** [comment]
Please go to:

https://explore.transifex.com/wishthis/wishthis/

you can join and help to complete the translation over there!

**Comment by ImAndr0meda** [comment]
Ok, I did it :)
