### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by PrivacyDragon** [wishthis/wishthis#36]
Another suggestion:
It looks like there currently are no image preview things, like, you do not see what the item is that is on the wish list, so you might first have to follow the URL to even get a proper indication of what it is.
However, the icon of the website where the URL leads to. In the same way it should be possible to show an image of the item or something like that.
For example, the Toki Pona Dictionary on bol.com, gives a page where in the `<head>` can be found: `<meta property="og:image" content="https://media.s-bol.com/qADwAr7K8zoy/vg4ENln/550x823.jpg">`.
That URL is an image of the item that the page shows. So that could probably be used to show what something is on the list. (Though it is probably true that it might not always work. But I think it works for most big web shops.)

**Comment by grandeljay** [comment]
Hey @PrivacyDragon,

thanks again for another suggestion!

I agree, link previews should be automatically set, when they are supplied by the website. For the sake of reproducibility, could you please provide me with some example links which fail to show the proper or any image?

**Comment by PrivacyDragon** [comment]
I have not found any link yet for which is shown an image.
URL's I tried:
https://www.bol.com/nl/nl/p/toki-pona-dictionary/9300000047079243/
https://onzetaalwebwinkel.nl/boeken-24/boeken/een-topjaar-voor-eikels
https://appelboom.com/nl/faber-castell-converter/
https://www.amazon.nl/Deeper-Waters-F-T-Lukens/dp/1534480501/ref=sr_1_1?crid=11IQC0OBXSP07

**Comment by grandeljay** [comment]
Thank you!

Ah yes, this was actually fixed a while back and should work if you switch to the release candidate of wishthis in your profile preferences.

I'm planing to publish my next release this year!

**Comment by PrivacyDragon** [comment]
Ah, that works indeed!
Though, somehow the website where I expected it the most to work, doesn't provide an image. (Amazon). (But that is probably just an Amazon problem.)
