### ISSUE TITLE
Quote Symbol (") in description crashes save

### ISSUE THREAD

**Issue by oliverhildner** [wishthis/wishthis#38]
When adding this text as description to a wish, the site crashes on save (blank screen):

WD Red SA500 NAS SATA SSD 2TB 2.5": Amazon.de: Computer & Accessories

The problem is the quotes-character after '2.5' as it works fine after it is removed.

Page: Wishthis.online (Wish 383)
Browser: Firefox

**Comment by grandeljay** [comment]
Hi @oliverhildner,

thanks for reporting this! This feels like a familiar issue and should be resolved if you switch to the release candidate of wishthis in your profile preferences. I plan to publish the release candidate version this year.

Can you please let me know if switching channels resolves your issue?

**Comment by grandeljay** [comment]
Nvm, I just updated wishthis, it should work either way for you now. Please let me know.

**Comment by oliverhildner** [comment]
@grandeljay, it works fine now. Thank you for your amazing work!
