### ISSUE TITLE
CSS :z-index conflict between (filter) dropdown menu and priority ribbon on wish card

### ISSUE THREAD

**Issue by Hiobi** [wishthis/wishthis#44]
Hi again,

A little CSS issue on ribbon : when the filter dropdown menu is unscrolled, the priority ribbon on wish card have an higher z-index priority, so this ribbon covered up dropdown menu.

I'm using Mozilla / Firefox 106.0.2-0.1 on Manjaro Linux. Resolution 1920 x 1080.

![wishthis_z-index](https://user-images.githubusercontent.com/2171856/199467336-03072daf-391a-4bc7-b855-1c9e36dc8251.png)

**Comment by grandeljay** [comment]
Thanks for reporting this! It should be working now.

![image](https://user-images.githubusercontent.com/45571053/199578591-92a8f99b-bc59-4608-afe4-78120817da68.png)
