### ISSUE TITLE
Charset issue (UTF-8 content) and special characters interpreting

### ISSUE THREAD

**Issue by Hiobi** [wishthis/wishthis#45]
Hi @grandeljay

It seems that the issue with charset UTF-8 special characters interpretation (as reported on [discord](https://discordapp.com/channels/935867122729496616/935867122729496619/1028389096634187807)) still occurred. 
When I wrote a text with special characters (semicolon, comma, etc), special characters aren't interpreted.
The issue didn't happened after you fixed it at first time, but it's re-happen every time I publish or edit a wish, since few days. 

I'm using [wishthis docker version](https://hub.docker.com/repository/docker/hiob/wishthis) > built on stable branch
- wishthis 0.7.0 version (stable branch) SHA [cf6cabdff487c263b41c4d994c6bfd5ed14ecdb6](https://github.com/grandeljay/wishthis/commit/cf6cabdff487c263b41c4d994c6bfd5ed14ecdb6)
- wishthis 0.7.0 docker version (stable branch) SHA [4555ce748288e251161ac36d3f54f163ba673e477e658afc1c28c8cdb2c22f7e](https://hub.docker.com/layers/hiob/wishthis/stable/images/sha256-4555ce748288e251161ac36d3f54f163ba673e477e658afc1c28c8cdb2c22f7e?context=repo)

--- 

Example link (UTF-8 content) used : https://hiob.fr/octoprint/

![wishthis_charset](https://user-images.githubusercontent.com/2171856/199476278-c8f1c8a5-22e9-4ca8-847e-a4b6f72e6c96.gif)

**Comment by grandeljay** [comment]
Looks like quotes were not being converted. Should be fixed now! Changes can be found in the release candidate for now.

![2022-11-02-16-53-26](https://user-images.githubusercontent.com/45571053/199539133-a5622092-02bf-4e14-8e51-d0bcf18950aa.gif)

**Comment by Hiobi** [comment]
Well done! 
I built and pushed new docker image > https://hub.docker.com/layers/hiob/wishthis/release-candidate/images/sha256-3ad92f6c02d784a985e1e73b3d1fe50a1f7f94fb9aebd02e5e0d89b6b509c781?context=repo
