### ISSUE TITLE
CSS/UI issues on mobile

### ISSUE THREAD

**Issue by Hiobi** [wishthis/wishthis#48]
Hi again,

Some CSS improvements for future, some elements aren't accessible  (out of frame, not clickable), or covered par others elements (z-index, etc). You can reproduce it on some devices with different resolution/OS: Android, iOS, Kindle, etc

_Dropdown menu alignment_
![wishthis_dropdown_alignment](https://user-images.githubusercontent.com/2171856/201040058-c7f77b34-af2c-4a9c-86b2-15dcff2d7524.JPEG)

_Unreadable price on dark mode_ ( [already reported](https://github.com/grandeljay/wishthis/issues/43#issuecomment-1309420759) )
![wishthis_price_darkmode](https://user-images.githubusercontent.com/2171856/201040091-afceda41-883d-4423-abc4-0e1a7e705c5d.JPEG)

Site title covered by priority ribbon (when title a bit to large)
![wishthis_title-covered-ribbon](https://user-images.githubusercontent.com/2171856/201040105-4195ea61-b6da-462b-ba5e-0f2e1c230d12.JPEG)

_Visit / Option button out of frame_
![wishthis_visit_button](https://user-images.githubusercontent.com/2171856/201040136-8ebc5464-b507-423c-a30e-21e73a2748af.JPEG)

**Comment by grandeljay** [comment]
The filter dropdown menu should be better now (v0.7.1)

**Comment by Hiobi** [comment]
Hi,
Thanks for improvements ! You did a great job ! I like how the buttons are displayed. 


> The filter dropdown menu should be better now (v0.7.1)


Unfortunately, I cannot test the dropdown, a new CSS issue appeared: covers the item above/below. There is no space between each, among other things you cannot click on the filter menu. I got this issue on an iPhone X (5"8 inches) >>  https://iob.wf/wishthisdev

I'm using docker version built this morning on develop branch.

![IMG_0548](https://user-images.githubusercontent.com/2171856/201491951-52fdf6e1-5fde-49ee-b59e-ff2437d60492.JPEG)

![IMG_0547](https://user-images.githubusercontent.com/2171856/201491941-75195656-9291-430c-8b31-ae16d00fcad3.JPEG)

**Comment by Hiobi** [comment]
Another issue found:

When a visitor click a "realize a wish" the priority ribbon covers the message about the temporary lock.

![IMG_0549](https://user-images.githubusercontent.com/2171856/201492517-3be43767-a4d3-4723-8401-abbf33601a19.JPEG)

**Comment by grandeljay** [comment]
Sorry about that, is it better now?

**Comment by Hiobi** [comment]
> Sorry about that, is it better now?

Solved ! Good job. ☺️


![image](https://user-images.githubusercontent.com/2171856/202637173-ccfe11c3-fd43-4751-926a-908906f7067e.jpeg)

![image](https://user-images.githubusercontent.com/2171856/202637198-c1b3ec07-b717-4577-bec0-e78795072cf3.jpeg)

**Comment by Hiobi** [comment]
hi again,
I spotted something on *remember list* button, when clicking on this button, it still white. The transition back seems to not happened. 

![wishthis_registeredlist_button](https://user-images.githubusercontent.com/2171856/202656553-b79f158e-15ad-4dac-853b-acb6c73d76aa.png)

**Comment by grandeljay** [comment]
Nice find!

I fixed the CSS for the button but just FYI: if you are on mobile, you need to tap something else (like the background) to de-select the button so it returns into its normal state again (it's currently focused).

**Comment by Hiobi** [comment]
Yeah ! I noticed that, Thanks for the tip. 

Sorry, I forgot the details on my previous comment, it was happen on latest FireFox for Manjaro. ☺️

Maybe We should rename this issue, if I report others comestic improvement, on other device than mobile?

**Comment by grandeljay** [comment]
> Maybe We should rename this issue, if I report others comestic improvement, on other device than mobile?

Sounds good. I just renamed it and if you find something wrong on the desktop version, best create a new issue for that! :)
