### ISSUE TITLE
Insufficient power: Restricted access (develop branch)

### ISSUE THREAD

**Issue by Hiobi** [wishthis/wishthis#56]
Hi,

On `develop branch` > docker image built _nov. 30, 2022 7:58pm GMT+0100_ with [this commit ](https://github.com/grandeljay/wishthis/commit/1606340af2f2e59f75d4e8beac707cd507b1f84e)as latest:

Only the admin account is able to use wishthis as a registered user.  With other users I get error on almost every page. They are not able to see their own _wishlists_, _remembered list_ or _profile_. Only the _homepage_ is accessible, like a guest user.

```PHP
Restricted access


Warning: Undefined array key "required" in /var/www/html/src/pages/power.php on line 23
You do not have enough power to view this page. You need to see this page, but only have 0.
```

Thanks @grandeljay !

**Comment by grandeljay** [comment]
Hey @Hiobi,

as you already noticed the `develop` branch is very unstable and constantly changing. I'm still modifying the database structure as I'm working on this release so we will have to occasionally make the changes to the database manually if you are using the `develop` branch.

This SQL command should fix the issue for you (the migration script will do this when you update from `v0.7.2`):
```sql
UPDATE
    `users`
SET
    `power` = 1
WHERE
    `power` = 0;
```

**Comment by Hiobi** [comment]
> as you already noticed the develop branch is very unstable and constantly changing. I'm still modifying the database structure as I'm working on this release so we will have to occasionally make the changes to the database manually if you are using the develop branch.

Don't worry, I didn't use `develop branch` in production. 😁
I'm trying to help you by reporting issues: I have an instance on `develop branch` to test it. 
For production, I use release-candidate. 

Thanks for the SQL command !
