### ISSUE TITLE
Only remove purchased/fulfilled wishes on the 'public' side of the list.

### ISSUE THREAD

**Issue by PrivacyDragon** [wishthis/wishthis#58]
Right now, when someone fulfills a wish, it is removed for everyone. This is good, because otherwise it could be bought twice or even more.
However, it is also removed for the person who made the list.
So whenever I look at the list to edit it and I see something's gone, that is a way to know what I will get.
I think this should probably change. Maybe it's possible to keep showing those items to the person who creates the list?
So, yes. This just happened to me. Now I know what I will receive. I hope it won't be too hard to fix this.
Maybe have two databases or something. Or have a field for whether an item has been fulfilled. With that latter option, only items that have not been checked as fulfilled can be shown and to the creator of the list all the items can be shown.

**Comment by grandeljay** [comment]
Hey @PrivacyDragon 

thanks for reporting this!

> So whenever I look at the list to edit it and I see something's gone, that is a way to know what I will get.

This is not intended behaviour, the items should remain in your list so you can get surprised. Just to clarify: you are looking at your list while logged into wishthis? Or are you viewing the link you shared with others?

**Comment by PrivacyDragon** [comment]
I am looking at the list while being logged in.
And I even created a testlist after discovering and put two things on it. In another browser I visited the share version and fulfilled the two items.
They were then gone too in the editing interface. So while logged in I didn't see the same two items, but an empty list.

**Comment by grandeljay** [comment]
Sorry about that!

I've just created a fix and updated all wishthis instances. Can you please confirm it works again for you?

**Comment by PrivacyDragon** [comment]
Yes, it works again properly again now!
Thank you so much for fixing this so soon!
