### ISSUE TITLE
Temporary fulfilled wish does not become available again after 30 minutes, except when viewing as the owner of the list.

### ISSUE THREAD

**Issue by GlitchCat** [wishthis/wishthis#71]
## Branch
On which branch did you notice this bug?
- [x] stable
- [x] release-candidate
- [ ] develop

Both version 0.7.3

## Description
1. Create a list and add a wish.
2. Copy the share link and open it in incognito.
3. Fulfill a wish temporarily and wait 30+ minutes. Do NOT confirm the wish as fulfilled.
4. Notice that the wish is not available again.
5. Refresh the page after nothing happening, noticing that the wish is still not available.

Waiting 60+ minutes also did not make the wish come back.

I also tested viewing the shared list url, after the wish was supposed to be available again, as a different logged in user and as the owner of the list.

It seems that the item in the list IS added back (after 30 minutes) in the shared wishlist for the owner, but anyone else (either logged in or anonymous) will not see the item returned after 30 minutes.

**Comment by GlitchCat** [comment]
Also, cool project :)
Seems to be the only (good) opensource one that I could find.
Thanks!

**Comment by grandeljay** [comment]
Hey @GlitchCat thank you for reporting this!

I've been really busy lately and so far unable to confirm this but it sounds very familiar and might already be fixed on the `develop` ([dev.wishthis.online](https://dev.wishthis.online)) branch.

If you have the time to test it there I would greatly appreciate your effort! Either way, thank you!

> Also, cool project :)
> Seems to be the only (good) opensource one that I could find.

Thanks! There seem to be plenty similar projects around, but I couldn't find a single one which was open source. all of them were commercial or just looking bad to me. For me, wishthis is a real problem solver and I am glad it's also useful to you (and others).

\- Jay

**Comment by GlitchCat** [comment]
Hey so while trying to test it i first tried to add something to a list on my previous temporary account, which gave a internal server error.

Noticing this i tried to create a new account on `dev.wishthis.online` specifically, but when trying to view it I got redirected to this page:
![image](https://user-images.githubusercontent.com/25588874/216397913-ee10a7f5-b297-46cb-b0c7-8a06fbf39289.png)

I'm pretty sure the online dev version is locked down, but I could try running the develop branch in docker :)

**Comment by grandeljay** [comment]
Yikes, there are more issues over there than I had hoped for.

I'll have a look at it then, thanks for trying!

**Comment by grandeljay** [comment]
I've just updated the release candidate and removed the temporary wish status for now. It seemed unintuitive for some users.

Let me know if you are still having issues.

**Comment by GlitchCat** [comment]
I tried testing the release candidate at `https://rc.wishthis.online/`, but I got the same restricted access issue as with the develop branch :\

Would help more with actual debugging or reviewing the code if I had the time, but I'm also not too familiar with PHP.

**Comment by grandeljay** [comment]
> tried to add something to a list on my previous temporary account,

You don't need to create a new account on the release candidate, it's sharing a database with the stable branch so you can just log in with your existing account

You can also just log into dev.wishthis.online with your existing account, it uses a copy of the live database from the stable branch.

> but I got the same restricted access issue as with the develop branch :\

I believe I found the error, can you please try again?

**Comment by GlitchCat** [comment]
Hi, it seems the 'restricted access' issue has been fixed on both the release candidate and the development version. :)

From the UI the temporary fulfilled wish feature is removed, as expected.
Note however that the `What to do?` instruction text still instructs about confirming the temporary fulfilled wish.
