### ISSUE TITLE
Error 500 after fresh install - Undefined constant "CHANNELS"

### ISSUE THREAD

**Issue by Beanux** [wishthis/wishthis#74]
## Branch
On which branch did you notice this bug?
- [ ] stable

## Description
A fresh install
And on the loading of the page, http 500.
Meaningfull logs:
`Got error 'PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "CHANNELS" in /XXXX/src/functions/redirect.php:22`
Commenting the loop after "/** Determine if host is a defined channel */" allow to bypass the issue.

Sin i don't know exactly what it's about, i'm just reporting it here

**Comment by grandeljay** [comment]
Hey @Beanux,

thanks for reporting this! I'll have a look at it.

**Comment by DieterKoblenz** [comment]
I'm getting the same error (via the unofficial Docker) after a fresh install.

Manually making a config.php and database will not solve this. I've contacted the Docker maintainer in the hope he can be of assistance.

**Comment by grandeljay** [comment]
Are you using the develop branch https://hub.docker.com/r/hiob/wishthis/tags? I have not released the newest changes yet.

**Comment by DieterKoblenz** [comment]
Yes, I have even tried a new setup. Still getting the same error, unfortunately.
