### ISSUE TITLE
Is there an official Docker image?

### ISSUE THREAD

**Issue by ItsNoted** [wishthis/wishthis#75]
I'd love to see a Docker image for wishthis for easy deployment. Any plans or am I overlooking it already?

Thanks!

**Comment by grandeljay** [comment]
Hey @ItsNoted,

there is no official docker image, and also none planned at this moment. An unofficial image is available though which I can recommend thanks to @hiobi!

https://hub.docker.com/r/hiob/wishthis

**Comment by grandeljay** [comment]
There have been some reports of issues with the docker image, hopefully this helps: https://discord.com/channels/935867122729496616/935867122729496619/1141430737644556388

**Comment by Hiobi** [comment]
Now it's seems official. 0:)
https://github.com/wishthis/docker

**Comment by grandeljay** [comment]
Closing this... Let me know if something is still unclear for you.
