### ISSUE TITLE
German special letters are not correctly displayed

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/wishthis#80]
## Branch
On which branch did you notice this bug?
- [x] stable
- [x] release-candidate
- [ ] develop

## Description
German special characters (called "Umlaute" like ä, ü, ö) are not correctly displayed in search results. Instead of 'ä' it displays '\&auml;'.

## Additional info
tested Browsers: Firefox, Chrome

## Screenshot
![Screenshot (14)](https://github.com/grandeljay/wishthis/assets/64123611/ba818639-b144-410f-a819-ccee961fc833)

**Comment by proud-nerd** [comment]
this also happens, when I create a wish with such a letter in any field like name or description, save it, and then edit it again
![grafik](https://github.com/grandeljay/wishthis/assets/64123611/29ac925e-627c-4df6-8e7d-8a0dc2e209ef)

**Comment by grandeljay** [comment]
Thanks for reporting this!
