### ISSUE TITLE
Add Support for other number delimiters than point

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/wishthis#82]
**Is your feature request related to a problem? Please describe.**
Some countries (like germany for example) do not use point ("9.99€") as a delimiter, but comma ("9,99€"). So when I enter 9,99€ as the price for a wish, it's converted to 999.00€.

**Describe the solution you'd like**
Best solution would be, if the delimiter would be somehow linked to the selected language

**Describe alternatives you've considered**
Another solution - that'd be a lot easier to implement I guess - would be to allow the user to choose their delimiter in user settings.

It would also be okay to only allow point as a delimiter and show an error message with a hint to use point instead of comma in case a user enters a comma.

**Additional context**
I didn't know if this would be considered a bug or a feature request, but considering the amount of work for some of the solutions, I decided to label it as a feature. Ofc, feel free to change this.

**Comment by grandeljay** [comment]
The solution might be to use [a native number input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). It should allow whatever format the user has set in their OS or browser settings.

**Comment by proud-nerd** [comment]
sounds like a perfect solution, simple and still does everything it needs to.

Here is a working stackblitz: https://stackblitz.com/edit/stackblitz-starters-gnun5x?file=src%2Fmain.ts, looks like it keeps the resulting value as a valid number with point, so no explicit need to change any backend logic.

I made the stackblitz for angular, because that's what I'm used to, but should work the same in plain js. You need to change the input value after changing the language to make it update the validity. Of course you can just emit the lang attribute at all and just use the browser settings. It's just there for convenience.
