### ISSUE TITLE
switching to "product" tab leads to tabview being in a broken state

### ISSUE THREAD

**Issue by proud-nerd** [wishthis/wishthis#83]
## Branch
On which branch did you notice this bug?
- [x] stable
- [x] release-candidate
- [ ] develop

## Description
- open a wish that can be bought and switch tab to "product"
- click close or save while that tab is opened
- open any item and switch to product tab

## Actual behaviour
the tab does not switch and stays at general view
![image](https://github.com/grandeljay/wishthis/assets/64123611/70cb2d84-a9c2-4886-b3e6-b5e9ffd9291d)

## Expected behaviour
it should switch to product view

## Additional info
- In some rare occasions I can't reproduce the error.
- In some cases the view for adding new wishes is stuck in a broken state after reproducing the error
![image](https://github.com/grandeljay/wishthis/assets/64123611/ee2253fb-c1e0-4fd7-abd3-589473997c30)

**Comment by grandeljay** [comment]
It seems to reliably break when you close the modal while the Product tab is open. As a workaround you can always switch to the Main tab and then save or abort.

Investigating why...
