### ISSUE TITLE
Uncaught Error: Undefined constant "CHANNELS"

### ISSUE THREAD

**Issue by UNICodehORN** [wishthis/wishthis#91]
## Branch
On which branch did you notice this bug?
- [x] stable
- [x] release-candidate
- [ ] develop

## Description
Fresh checkout on ubuntu with php8.2 (stable & also tried release-candidate).
Error in apache log: "Uncaught Error: Undefined constant "CHANNELS [...] src/functions/redirect.php on line 23"

I tried to initialize the constant with "null", this loads the installer page, however then after entering the db credentials the installer hangs in step two with a black screen. Developer tools only show problems with "plausible.io", but I suspect this is not the real error.

**Comment by grandeljay** [comment]
Hey @UNICodehORN, thanks for reporting this! 

This seems to be a duplicate which I have already addressed (but not released): #74.

In the meantime, as a workaround, you could define the constant in your config like here: [config-sample.php](https://github.com/grandeljay/wishthis/blob/develop/src/config/config-sample.php).

**Comment by UNICodehORN** [comment]
Thanks for the fast reply. I checked the issue and solved by doing the following:

1. Copy src/config/config-sample.php to config.php
2. Edit config.php and inserted db credentials.
3. Finished installation

Afterwards I checked out the develop branch to have the latest changes available for testing.
